# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
  
# Licensed under the Apache License, Version 2.0 (the "License").
# You may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#     http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
    exchange(n::Int) = n - (-1)^mod(n, 2)
Performs the following exchanges:
1<=>2, 3<=>4, 5<=>6, etc.

Notes:
    If the stabilizers are non CSS, we need to use the symplectic form to 
    multiply the syndrome and stabilizer vectors. This is effectively 
    done via the exchange function
"""
exchange(n::Int) = n - (-1)^mod(n, 2)


"""
    decode_concatenated_rectangular_GKP_code(
        x::Vector, 
        stabilizers::Dict{Int64, Vector{Int64}},
        η::Vector
        )

Decode a concatenated rectangular GKP code for an input vector x. 

Inputs:
    x: The input vector
    stabilizers: The stabilizers for the concatenated GKP code    
    η: The square root of aspect ratio for each lattice dimension
    type_stabilizers: The type of stabilizers, either "CSS" or others (treated as "non-CSS")

Outputs:
    y: The closest point for x in the symplectic dual lattice generated by √(2π) * Mperp
    final_list: The logical operator after the attempt of correcting the error

Note 1: 
    There are two assumptions for the concatenated GKP code
        1. The stabilizers should be chosen such that a given shift 
            error can induce at most two syndrome errors
        2. The inner GKP code has to be one mode rectangular GKP code
    
Note 2:
    If type_stabilizers == "CSS", then the input `stabilizers` is either the X or Z type stabilizers
"""
function decode_concatenated_rectangular_GKP_code(
    x::Vector, 
    stabilizers::Dict{Int64, Vector{Int64}}, 
    η::Vector;
    type_stabilizers::String="CSS"
)

    if type_stabilizers != "CSS" && type_stabilizers != "non-CSS"
        @warn("`type_stabilizers` should be either `CSS` or `non-CSS`. 
            Anything other than `CSS` will be treated as `non-CSS`.")
    end
    if type_stabilizers == "non-CSS"
        stabilizers2 = Dict{Int64, Vector{Int64}}()
        for (key, val) in stabilizers
            stabilizers2[key] = exchange.(val)
        end
        stabilizers = stabilizers2
    end
    
    # The following is the same regardless if type_stabilizers == "non-CSS" or not

    x = x/√π ./η
    
    # get the weights for each qubit, which are the edges of the graph
    closest_integers = closest_integer.(x)
    second_closest_integers = second_closest_integer.(x)

    edge_weight_list = ((second_closest_integers.-x).^2 - (closest_integers.-x).^2) .* η.^2

    # get edge_to_mode_dict
    num_vertices = length(stabilizers)+1
    keys_stabilizers = collect(keys(stabilizers))
    values_stabilizers = collect(values(stabilizers))
    edge_to_mode_dict = Dict()
    for qubit in 1 : length(x)
        qubit_in_stab = findall(qubit .∈ values_stabilizers) # determine which stabilizers the qubit is in
        if length(qubit_in_stab) > 2
            error("Cannot decode code where a single fault can lead more than 2 errors.")
        elseif length(qubit_in_stab) == 2
            vertex_1, vertex_2 = keys_stabilizers[qubit_in_stab[1]], keys_stabilizers[qubit_in_stab[2]]
        elseif length(qubit_in_stab) == 1
            vertex_1, vertex_2 = keys_stabilizers[qubit_in_stab[1]], num_vertices
        elseif length(qubit_in_stab) == 0 # ignore if the qubit is not in any stabilizers
            continue
        end

        if Set([vertex_1, vertex_2]) in keys(edge_to_mode_dict)
            if edge_weight_list[qubit] < edge_to_mode_dict[Set([vertex_1, vertex_2])][2]
                edge_to_mode_dict[Set([vertex_1, vertex_2])] = (qubit, edge_weight_list[qubit])
            end
        else
            merge!(edge_to_mode_dict, Dict(Set([vertex_1, vertex_2]) => (qubit, edge_weight_list[qubit])))
        end
    end

    # highlight the unhappy stabilizers/vertices
    highlighted_vertices = zeros(Int, num_vertices)
    for (index, stabilizer) in stabilizers
        if mod(sum(closest_integers[stabilizer]), 2) == 1
            highlighted_vertices[index] = 1
        end
    end

    highlighted_vertices[num_vertices] = mod(sum(highlighted_vertices), 2)
    
    # Get the weights of the graph
    g = Matrix(0.0I, num_vertices, num_vertices)
    for (key, (qubit, weight)) in edge_to_mode_dict
        vertex_1, vertex_2 = collect(key)[1], collect(key)[2]
        g[vertex_1, vertex_2] = weight
    end
    g = g + transpose(g)

    
    paths = mwpm(g, highlighted_vertices)
    
    correction_list = zeros(Int, length(x))
    for (i, j) in paths
        correction_list[edge_to_mode_dict[Set([i,j])][1]] += 1
    end

    # Get the closest point 
    cp = [
        if (correction == 1) second_closest_integers[i] else closest_integers[i] end 
            for (i, correction) in enumerate(correction_list)
    ]

    error_list = mod.(closest_integers, 2)
    final_list = correction_list - error_list

    y = cp .* √π .* η
    return y, final_list
end


"""
    decode_concatenated_GKP_code(x::Vector, stabilizers::Dict{Int64, Vector{Int64}}; type_stabilizers::String="CSS")

Decode a concatenated square GKP code for an input vector x.

Inputs:
    x: The input vector
    stabilizers: The stabilizers for the concatenated GKP code    
    type_stabilizers: The type of stabilizers, either "CSS" or others (treated as "non-CSS")

Outputs:
    y: The closest point for x in the symplectic dual lattice generated by √(2π) * Mperp
    final_list: The logical operator after the attempt of correcting the error

Note 1: 
    There are two assumptions for the concatenated GKP code
        1. The stabilizers should be chosen such that a given shift 
            error can induce at most two syndrome errors
        2. The inner GKP code has to be one mode square GKP code
    
Note 2:
    If type_stabilizers == "CSS", then the input `stabilizers` is either the X or Z type stabilizers
"""
decode_concatenated_GKP_code(x::Vector, stabilizers::Dict{Int64, Vector{Int64}}; type_stabilizers::String="CSS") = decode_concatenated_rectangular_GKP_code(x, stabilizers, ones(length(x)), type_stabilizers=type_stabilizers)

